USE ROLE ACCOUNTADMIN;

CREATE FILE FORMAT IF NOT EXISTS RP_FF_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', '');

CREATE FILE FORMAT IF NOT EXISTS RP_FF_PARQUET
    TYPE = PARQUET;